/*
 * SPDX-FileCopyrightText: Copyright (C) 2018-2025 Fabrício Barros Cabral
 * SPDX-License-Identifier: MIT
 */
package com.github.fabriciofx.cactoos.jdbc.connection;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Transacted connection.
 *
 * @since 0.1
 * @checkstyle ParameterNameCheck (500 lines)
 * @checkstyle ParameterNumberCheck (500 lines)
 * @checkstyle TooManyMethods (500 lines)
 */
@SuppressWarnings(
    {
        "PMD.TooManyMethods",
        "PMD.LongVariable"
    }
)
public final class Transacted extends ConnectionEnvelope {
    /**
     * The connection.
     */
    private final Connection origin;

    /**
     * Number of created statements.
     */
    private final AtomicInteger stmts;

    /**
     * Ctor.
     * @param connection A Connection
     */
    public Transacted(final Connection connection) {
        super(connection);
        this.origin = connection;
        this.stmts = new AtomicInteger(0);
    }

    @Override
    public Statement createStatement() throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(final String sql) throws
        SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(final String sql) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareCall(sql);
    }

    @Override
    public void setAutoCommit(final boolean autoCommit) throws SQLException {
        // Don't allow change the auto commit state
    }

    @Override
    public void commit() throws SQLException {
        this.origin.commit();
        this.stmts.set(0);
    }

    @Override
    public void rollback() throws SQLException {
        this.origin.rollback();
        this.stmts.set(0);
    }

    @Override
    public void close() throws SQLException {
        if (this.stmts.get() == 0) {
            this.origin.close();
        }
    }

    @Override
    public Statement createStatement(
        final int resultSetType,
        final int resultSetConcurrency
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.createStatement(resultSetType, resultSetConcurrency);
    }

    @Override
    public PreparedStatement prepareStatement(
        final String sql,
        final int resultSetType,
        final int resultSetConcurrency
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareStatement(
            sql,
            resultSetType,
            resultSetConcurrency
        );
    }

    @Override
    public CallableStatement prepareCall(
        final String sql,
        final int resultSetType,
        final int resultSetConcurrency
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareCall(
            sql,
            resultSetType,
            resultSetConcurrency
        );
    }

    @Override
    public Statement createStatement(
        final int resultSetType,
        final int resultSetConcurrency,
        final int resultSetHoldability
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.createStatement(
            resultSetType,
            resultSetConcurrency,
            resultSetHoldability
        );
    }

    @Override
    public PreparedStatement prepareStatement(
        final String sql,
        final int resultSetType,
        final int resultSetConcurrency,
        final int resultSetHoldability
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareStatement(
            sql,
            resultSetType,
            resultSetConcurrency,
            resultSetHoldability
        );
    }

    @Override
    public CallableStatement prepareCall(
        final String sql,
        final int resultSetType,
        final int resultSetConcurrency,
        final int resultSetHoldability
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareCall(
            sql,
            resultSetType,
            resultSetConcurrency,
            resultSetHoldability
        );
    }

    @Override
    public PreparedStatement prepareStatement(
        final String sql,
        final int autoGeneratedKeys
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(
        final String sql,
        final int[] columnIndexes
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareStatement(sql, columnIndexes);
    }

    @Override
    public PreparedStatement prepareStatement(
        final String sql,
        final String[] columnNames
    ) throws SQLException {
        this.stmts.getAndIncrement();
        return this.origin.prepareStatement(sql, columnNames);
    }
}
